include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Sugestões de `const` desligadas para reduzir ruído neste estágio de UI.
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
